Repository DDD-Community/Rainbow-Web, pull requests merged in 2023-09, with the labels that each got.

#57 refactor: onboarding errorcase
  .env
  .vscode/settings.json
  cypress.config.js
  next.config.js
  public/assets/images/icons/index.ts
  public/assets/images/icons/logo-buybye.svg
  public/assets/images/icons/logo-kakao.svg
  src/api/auth/client.tsx
  src/app/member/kakao/LoginHandler.tsx
  src/app/member/kakao/Start.tsx
  src/app/member/kakao/page.tsx
  src/app/onboarding/birth/page.tsx
  src/app/onboarding/checking/page.tsx
  src/app/onboarding/contract/page.tsx
  src/app/onboarding/email/page.tsx
  src/app/onboarding/following/page.tsx
  src/app/onboarding/gender/page.tsx
  src/app/onboarding/nickname/page.tsx
  src/app/onboarding/salary/page.tsx
  src/app/page.tsx
  src/components/Common/Input/TextInputBorder.tsx
  src/components/Common/Select/SelectEmail.tsx
  src/components/defaultContainer/index.tsx
  src/constant/api.constant.ts
  src/hooks/FormSubmitComponent.ts
  src/recoil/user.atoms.ts
  src/styles/font.css
  src/styles/globals.css
  tailwind.config.js
Labels: refactor

#62 카카오 로그인 + 회원가입
  src/styles/font.css
Labels: feat

#68 feat: loading화면 설정
  public/assets/motions/index.ts
  public/assets/motions/loading-spinner.json
  src/app/layout.tsx
  src/components/loading/index.tsx
Labels: feat

#67 Main 페이지 제작
  package-lock.json
  package.json
  public/assets/images/icons/checked.svg
  public/assets/images/icons/index.ts
  public/assets/images/icons/pen.svg
  src/app/main/page.tsx
  src/app/member/kakao/Start.tsx
  src/app/onboarding/contract/page.tsx
  src/app/onboarding/following/page.tsx
  src/app/page.tsx
  src/components/calender/index.tsx
  src/components/logout/index.tsx
  src/components/recordPage/EmblaCarousel.tsx
  src/components/recordPage/RecordPage.tsx
  src/components/recordPage/UserFeedList.tsx
  src/components/userCard/index.tsx
Labels: feat

#70 feat: 목표금액 설정 component
  src/app/main/page.tsx
  src/components/monthlyTarget/index.tsx
Labels: feat

#71 Feat/plus page#42
  public/assets/images/icons/circleX.tsx
  public/assets/images/icons/search.tsx
  public/assets/images/icons/xMark.tsx
  src/app/plus/category/page.tsx
  src/app/plus/category/reg/page.tsx
  src/app/plus/cost/footer.tsx
  src/app/plus/cost/page.tsx
  src/app/plus/cost/section.tsx
  src/app/plus/detail/footer.tsx
  src/app/plus/detail/page.tsx
  src/app/plus/detail/section.tsx
  src/app/plus/layout.tsx
  src/app/plus/reg/page.tsx
  src/components/Common/Button/Button.tsx
  src/components/Common/Button/Contained/Primary/PrimaryButton.tsx
  src/components/Common/Button/Contained/Sub/SubButton.tsx
  src/components/Common/Button/Rounded/Sub/RoundedButton.tsx
  src/components/categoryCard/index.tsx
  src/components/navigationBar/index.tsx
  src/components/noResult/index.tsx
  src/components/noText/index.tsx
  src/components/searchBar/index.tsx
  src/components/toggle/index.tsx
  src/recoil/plus.atoms.ts
  src/types/utils/utils.ts
  types.d.ts
Labels: feat, v1

#59 Feat/bottom navigation bar#56
  public/assets/images/icons/bottomNavigationBar/alarm.tsx
  public/assets/images/icons/bottomNavigationBar/expense.tsx
  public/assets/images/icons/bottomNavigationBar/feed.tsx
  public/assets/images/icons/bottomNavigationBar/my.tsx
  src/app/feed/page.tsx
  src/app/layout.tsx
  src/components/bottomNavigationBar/index.tsx
  src/components/defaultContainer/index.tsx
  src/hooks/useFooterNavBar.ts
  src/recoil/footerNavBar.atoms.ts
  src/styles/globals.css
  types.d.ts
Labels: feat, v1, refactor

#74 fix: atom key 수정#73
  src/recoil/footerNavBar.atoms.ts
Labels: bug

#76 Feat/feed nickname search#75
  public/assets/images/emotion/no-text.tsx
  public/assets/images/icons/back.tsx
  src/app/feed/nickNameSearch.tsx
  src/app/feed/page.tsx
  src/components/noResult/index.tsx
  src/components/searchBar/index.tsx
Labels: feat, v1

#78 style: defaultContainer 첫번째 요소 height 설정#77
  src/components/defaultContainer/index.tsx
Labels: bug, v1

#79 Feat/feed api#60
  .eslintrc.json
  public/assets/images/emotion/angry.tsx
  public/assets/images/emotion/happy.tsx
  public/assets/images/emotion/plus.tsx
  public/assets/images/emotion/sad.tsx
  public/assets/images/emotion/surprised.tsx
  public/assets/images/emotion/thinking.tsx
  public/assets/images/icons/search.tsx
  src/app/feed/feedHandler.tsx
  src/app/feed/page.tsx
  src/components/card/index.tsx
  src/components/emojiBottomSheet/index.tsx
  src/components/userFeedCard/index.tsx
Labels: feat, v1

#83 feat: 알림 페이지 마크업 #82
  src/app/alarm/page.tsx
Labels: feat, v1
