Repository DDD-Community/Rainbow-Web, pull requests merged in 2023-08, with the labels that each got.

#22 feat: search bar 개발 완료 커밋 #16
  components/searchBar/index.tsx
Labels: feat, v1

#26 Feat/bottom sheet#25
  app/globals.css
  assets/styles/bottomSheet.css
  components/bottomSheet/index.tsx
  package-lock.json
  package.json
Labels: feat, v1

#29 Feat/emoji bottom sheet#24
  assets/images/emotion/index.ts
  assets/images/emotion/surprised.svg
  components/emojiBottomSheet/index.tsx
  types.d.ts
Labels: feat, v1

#35 Feat/profile component#34
  assets/images/icons/check.tsx
  assets/images/icons/plus.tsx
  assets/images/profile/emoji.tsx
  assets/images/profile/person.tsx
  components/emojiProfile/index.tsx
  components/personProfile/index.tsx
  components/profile/index.tsx
Labels: feat, v1

#32 Refactor/feed card#31
  .eslintrc.json
  components/card/index.tsx
  components/feedCard/index.tsx
  components/userFeedCard/feedCard.tsx
  components/userFeedCard/index.tsx
Labels: v1, refactor

#33 Feat/feed page markup#16
  app/feed/page.tsx
  components/card/index.tsx
  components/searchBar/index.tsx
  components/userFeedCard/feedCard.tsx
  components/userFeedCard/index.tsx
Labels: feat, v1

#36 내 지출 페이지 Calender Component 제작
  public/assets/images/profile/emoji.tsx
  public/assets/images/profile/person.tsx
  src/components/calender/index.tsx
  src/components/emojiProfile/index.tsx
  src/components/personProfile/index.tsx
Labels: feat

#43 Feat/ onboarding page
  cypress/e2e/main/main.cy.js
  cypress/support/commands.js
  next.config.js
  package-lock.json
  package.json
  public/assets/images/icons/exclamationMark.svg
  public/assets/motions/index.ts
  public/assets/motions/intro.json
  public/assets/motions/onboarding-motion.json
  src/app/layout.tsx
  src/app/member/kakao/LoginHandler.tsx
  src/app/member/kakao/Start.tsx
  src/app/member/kakao/page.tsx
  src/app/onboarding/birth/page.tsx
  src/app/onboarding/checking/page.tsx
  src/app/onboarding/contract/page.tsx
  src/app/onboarding/email/page.tsx
  src/app/onboarding/following/page.tsx
  src/app/onboarding/gender/page.tsx
  src/app/onboarding/nickname/page.tsx
  src/app/onboarding/page.tsx
  src/app/onboarding/salary/page.tsx
  src/app/page.tsx
  src/components/Common/Button/ButtonField.tsx
  src/components/Common/Button/Contained/Primary/PrimaryButton.tsx
  src/components/Common/Input/TextInputBorder.tsx
  src/components/Common/Select/Select.tsx
  src/components/Common/Select/SelectEmail.tsx
  src/components/Common/Select/SelectSalary.tsx
  src/components/Common/Select/index.tsx
  src/components/Information/Information.tsx
  src/components/defaultContainer/index.tsx
  src/constant/select.constant.ts
  src/hooks/FormSubmitComponent.ts
  src/hooks/LottieAnimation.tsx
  src/recoil/user.atoms.ts
  src/styles/font.css
  src/styles/globals.css
  tailwind.config.js
Labels: feat

#50 refactor: 온보딩 체킹 수정 버튼
  src/app/onboarding/birth/page.tsx
  src/app/onboarding/checking/page.tsx
  src/app/onboarding/gender/page.tsx
  src/app/onboarding/nickname/page.tsx
  src/recoil/user.atoms.ts
Labels: refactor

#53 style: pretendard 폰트 적용#52
  public/fonts/Pretendard-Black.woff2
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-ExtraBold.woff2
  public/fonts/Pretendard-ExtraLight.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  public/fonts/Pretendard-Thin.woff2
  src/styles/font.css
Labels: feat
